name: manga_tracking_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1
s
dependencies:
  flutter:
    sdk: flutter
  dynamic_color: ^1.7.0
  image_picker: ^1.1.2
  firebase_core: ^3.12.1
  firebase_database: ^11.3.4
  firebase_storage: ^12.4.4
  intl: ^0.20.2
  flutter_local_notifications: ^19.0.0
  permission_handler: ^11.3.0
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
